config/routes.rb
Rails.application.routes.draw do

  root 'homes#index'

  get 'users/new' => 'users#new'
  post 'users' => 'users#create'

  get 'users' => 'users#index'
  get 'users/:id' => 'users#show', as: :user

  get 'users/:id/edit' => 'users#edit', as: :edit
  patch 'users/:id' => 'users#update'

  delete 'users/:id' => 'users#destroy', as: :delete

end

app/models/sexe.rb
class Sexe < ActiveRecord::Base
  has_many :users
end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :sexe

  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.save
      redirect_to '/users'
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      redirect_to :action => 'show', :id => @user.id
    else
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      redirect_to '/users'
    else
      redirect_to :action => "show", :id => @user.id
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :age, :image, :sexe_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def active_class(link_path)
		active = current_page?(link_path) ? "active" : ""
	end
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/index.html.erb
<div class="section no-pad-bot" id="index-banner">
  <div class="container">
    <br><br>
    <h1 class="header center orange-text">Hello, world!</h1>
    <div class="row center">
      <h5 class="header col s12 light">Show all users in this word with this fabulous web application.</h5>
    </div>
    <div class="row center">
      <%= link_to "Learn more >>", '/users', class: "btn-large waves-effect waves-red orange", id:"download-button" %>
    </div>
    <br><br>
  </div>
</div>

<div class="section">

  <!--   Icon Section   -->
  <div class="row">
    <div class="col s12 m4">
      <div class="icon-block">
        <h2 class="center light-blue-text"><i class="material-icons">flash_on</i></h2>
        <h5 class="center">Speeds up development</h5>

        <p class="light">We did most of the heavy lifting for you to provide a default stylings that incorporate our custom components. Additionally, we refined animations and transitions to provide a smoother experience for developers.</p>
      </div>
    </div>

    <div class="col s12 m4">
      <div class="icon-block">
        <h2 class="center light-blue-text"><i class="material-icons">group</i></h2>
        <h5 class="center">User Experience Focused</h5>

        <p class="light">By utilizing elements and principles of Material Design, we were able to create a framework that incorporates components and animations that provide more feedback to users. Additionally, a single underlying responsive system across all platforms allow for a more unified user experience.</p>
      </div>
    </div>

    <div class="col s12 m4">
      <div class="icon-block">
        <h2 class="center light-blue-text"><i class="material-icons">settings</i></h2>
        <h5 class="center">Easy to work with</h5>

        <p class="light">We have provided detailed documentation as well as specific code examples to help new users get started. We are also always open to feedback and can answer any questions a user may have about Materialize.</p>
      </div>
    </div>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.3/css/materialize.min.css">
  <title>Turtle</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="navbar-fixed">
	<nav role="navigation">
		<div class="nav-wrapper container">
			<%= link_to "Hello Mongo", "/", { :class=>"brand-logo" } %>
			<a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
			<ul class="right hide-on-med-and-down">
				<li class="<%= active_class('/') %>"> <%= link_to "Home", "/"%> </li>
				<li class="<%= active_class('/userss') %>"><%= link_to "Users", '/users' %></li>
				<li><a href="#">About</a></li>
				<li><a href="#">Contact</a></li>
			</ul>
			<ul class="side-nav" id="mobile-demo">
				<li class="<%= active_class('/') %>"> <%= link_to "Home", "/"%> </li>
				<li class="<%= active_class('/users') %>"> <%= link_to "Users", '/users' %></li>
				<li><a href="#">About</a></li>
				<li><a href="#">Contact</a></li>
			</ul>
		</div>
	</nav>
</div>

<div class="container">
<%= yield %>
</div>

<footer class="page-footer">
  <div class="container">
    <div class="row">
      <div class="col l6 s12">
        <h5 class="white-text">Footer Content</h5>
        <p class="grey-text text-lighten-4">The application tou help you to devellope your skill.<br>
					Every one Every where you can change your life !. <br>
					Join Million of users and contribute to developpe this world.
				</p>
      </div>
      <div class="col l4 offset-l2 s12">
        <h5 class="white-text">Links</h5>
        <ul>
          <li class="<%= active_class('/') %>"> <%= link_to "Home", "/", :class=>"grey-text text-lighten-3"%> </li>
					<li class="<%= active_class('/userss') %>"> <%= link_to "Users", '/users', :class=>"grey-text text-lighten-3" %></li>
					<li><a href="#" class="grey-text text-lighten-3">About</a></li>
					<li><a href="#" class="grey-text text-lighten-3">Contact</a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container">
    © 2016 Copyright Z@ANKY
    <a class="grey-text text-lighten-4 right" href="#!">Contact</a>
    </div>
  </div>
	</footer>


</body>
</html>

app/views/users/edit.html.erb
<div class="row">
  <h1>Edit User</h1>

  <%= form_for @user, :html => {class: 'col s12'} do |u| %>
    <div class="row">
      <div class="input-field col s12 m6">
        <%= u.label :first_name, "First Name :" %>
        <p style="color: red"> <%= @user.errors[:title].first %> </p>
        <%= u.text_field :first_name, value: @user.first_name%>
      </div>
      <div class="input-field col s12 m6">
        <%= u.label :last_name, "Last Name :" %>
        <p style="color: red"> <%= @user.errors[:title].first %> </p>
        <%= u.text_field :last_name, value: @user.last_name%>
      </div>
    </div>
    <div class="row">
      <div class="input-field col s12 m6">
        <p style="color: red"> <%= @user.errors[:sexe_id].first %> </p>
        <%= u.select :sexe_id, Sexe.all.collect { |t| [t.title, t.id ] }, {include_blank: true}%>
        <%= u.label :sexe_id, "Sexe :" %>
      </div>
      <div class="input-field col s3 m1">
        <%= u.label :age, "Age :" %>
        <p style="color: red"> <%= @user.errors[:title].first %> </p>
        <%= u.number_field :age, value: @user.age%>
      </div>
    </div>
    <div class="row">
      <div class="input-field col s12 m6">
        <%= u.label :image, "Image link :" %>
        <p style="color: red"> <%= @user.errors[:title].first %> </p>
        <%= u.text_field :image, value: @user.image%>
      </div>
    </div>
    <div class="row">
      <div class="input-field col s6 m6">
        <%= u.submit 'Update', class: 'btn waves-effect waves-light' %>
      </div>
      <div class="input-field col s6 m6">
        <%= link_to "Cancel", user_path(@user), class: "btn waves-effect waves-red red", id:"download-button" %>
      </div>
    </div>
  <% end %>
</div>

app/views/users/index.html.erb
<div class="row">
	<div class="col s12 m12" style="margin-top: 30px">
		<table class="striped">
				<thead>
					<td><strong># </strong></td>
					<td><strong>First Name </strong></td>
					<td> <strong>Last Name </strong></td>
					<td> <strong>Sexe </strong></td>
					<td> <strong>Age </strong></td>
					<td>
						<%= link_to '/users/new', class: 'btn-floating btn-large waves-effect waves-light red' do %>
						  <i class="material-icons">add</i>
						<% end %>
					</td>
				</thead>
				<tbody>
					<% @users.each do |u| %>
					<tr>
						<td><%= u.id %></td>
	  					<td><%= u.first_name %></td>
	  					<td><%= u.last_name %></td>
	  					<td><%= u.sexe.title if u.sexe %></td>
	  					<td><%= u.age%> ans</td>
	  					<td><%= link_to "Learne more", user_path(u) %></td>
					</tr>
					<% end %>
				</tbody>
		</table>
	</div>
</div>

app/views/users/new.html.erb
<div class="row">
  <h1>Add Users</h1>

  <%= form_for @user, :html => {class: 'col s12'} do |u| %>
    <div class="row">
      <div class="input-field col s12 m6">
        <%= u.label :first_name, "First Name :" %>
        <p style="color: red"> <%= @user.errors[:title].first %> </p>
        <%= u.text_field :first_name%>
      </div>
      <div class="input-field col s12 m6">
        <%= u.label :last_name, "Last Name :" %>
        <p style="color: red"> <%= @user.errors[:title].first %> </p>
        <%= u.text_field :last_name%>
      </div>
    </div>
    <div class="row">
      <div class="input-field col s12 m6">
        <p style="color: red"> <%= @user.errors[:sexe_id].first %> </p>
        <%= u.select :sexe_id, Sexe.all.collect { |t| [t.title, t.id ] }, {include_blank: true}%>
        <%= u.label :sexe_id, "Sexe :" %>
      </div>
      <div class="input-field col s3 m1">
        <%= u.label :age, "Age :" %>
        <p style="color: red"> <%= @user.errors[:title].first %> </p>
        <%= u.number_field :age%>
      </div>
    </div>
    <div class="row">
      <div class="input-field col s12 m6">
        <%= u.label :image, "Image link :" %>
        <p style="color: red"> <%= @user.errors[:title].first %> </p>
        <%= u.text_field :image%>
      </div>
    </div>
    <div class="row">
      <div class="input-field col s6 m6">
        <%= u.submit 'Add', class: 'btn waves-effect waves-light' %>
      </div>

      <div class="input-field col s6 m6">
        <%= link_to "Cancel", '/users', class: "btn waves-effect waves-red red", id:"download-button" %>
      </div>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="row card-panel" style="margin-top: 40px">
	<div class="col s4 m6">
		<%= image_tag @user.image, :class => "circle responsive-img"%>
	</div>
	<div class="col s4 m6">
		<p class="flow-text"><%= @user.first_name %> <%= @user.last_name %></p>
		<p class="flow-text"> <%= @user.sexe.title if @user.sexe %> </p>
		<p class="flow-text"> <%= @user.age %> ans</p>
	</div>
	<div class="col s4 m6">
		<%= link_to '/users', class: 'btn-floating btn-large waves-effect waves-light red' do %>
			<i class="material-icons">face</i>
		<% end %>
		<%= link_to edit_path(@user), class: 'btn-floating btn-large waves-effect waves-light red' do %>
			<i class="material-icons">mode_edit</i>
		<% end %>
		<%= link_to delete_path(@user), method: 'delete', class: 'btn-floating btn-large waves-effect waves-light red' do %>
			<i class="material-icons">delete</i>
		<% end %>
	</div>
</div>